[package]
name = "ksuid-cli"
version = "0.1.0"
authors = ["Dylan MacKenzie <ecstaticmorse.gmail.com>"]

[dependencies]
docopt = "0.8.0"
ksuid = { version="0.1.0", path = ".." }
rand = "0.3.15"
serde = "1.0.8"
serde_derive = "1.0.8"
time = "0.1.37"
